services:
  - docker
install:
 - 'docker-compose build web mongo'
 - 'docker-compose run web composer build'
script:
 - 'docker-compose run web composer lint'
 - 'docker-compose run web composer test'
deploy:
  - provider: script
    skip_cleanup: true
    script: ./deploy.sh staging
    on:
      branch: develop