contents:
  resource: "map.controller.contents"
  type: rest

teams:
  resource: "map.controller.teams"
  type: rest

users:
  resource: "map.controller.users"
  type: rest

skills:
  resource: "map.controller.skills"
  type: rest

events:
  resource: "map.controller.events"
  type: rest

auth:
  resource: "map.controller.auth"
  type: rest

client:
  path: /
  defaults: { _controller: MapBundle:Home:index }
